"""empty message

Revision ID: c02cf653e161
Revises: 
Create Date: 2024-09-07 12:22:15.723815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02cf653e161'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('profile_img_url', sa.String(length=120), nullable=False),
    sa.Column('blood_type', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('birthdate', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('emergency_phone', sa.Integer(), nullable=False),
    sa.Column('stature', sa.String(length=120), nullable=False),
    sa.Column('weight', sa.String(length=120), nullable=False),
    sa.Column('objectives', sa.String(length=250), nullable=False),
    sa.Column('payement_type', sa.String(length=120), nullable=False),
    sa.Column('refered', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('birthdate'),
    sa.UniqueConstraint('blood_type'),
    sa.UniqueConstraint('emergency_phone'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('objectives'),
    sa.UniqueConstraint('payement_type'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('profile_img_url'),
    sa.UniqueConstraint('refered'),
    sa.UniqueConstraint('stature'),
    sa.UniqueConstraint('weight')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=120), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.String(length=120), nullable=False),
    sa.Column('end_date', sa.String(length=120), nullable=False),
    sa.Column('disciplines', sa.String(length=250), nullable=False),
    sa.Column('memmer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['memmer_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership')
    op.drop_table('user')
    op.drop_table('member')
    # ### end Alembic commands ###
