"""gym

Revision ID: ce72d8bffc19
Revises: 88b5d06a7a2b
Create Date: 2024-09-12 17:49:19.898207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce72d8bffc19'
down_revision = '88b5d06a7a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('stature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=120),
               existing_nullable=False)

    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.String(length=120),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('stature',
               existing_type=sa.String(length=120),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
