"""empty message

Revision ID: d8038d350ea0
Revises: a243437bfec8
Create Date: 2024-09-07 13:36:43.146611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8038d350ea0'
down_revision = 'a243437bfec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discipline', schema=None) as batch_op:
        batch_op.drop_constraint('discipline_membership_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'membership', ['membership_id'], ['id'])

    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_column('disciplines')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img_url', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['profile_img_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_img_url')

    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disciplines', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    with op.batch_alter_table('discipline', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('discipline_membership_id_fkey', 'member', ['membership_id'], ['id'])

    # ### end Alembic commands ###
