"""empty message

Revision ID: f11c5fe2122d
Revises: d8038d350ea0
Create Date: 2024-09-07 17:36:39.854428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11c5fe2122d'
down_revision = 'd8038d350ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discipline', schema=None) as batch_op:
        batch_op.drop_constraint('discipline_name_key', type_='unique')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint('member_address_key', type_='unique')
        batch_op.drop_constraint('member_birthdate_key', type_='unique')
        batch_op.drop_constraint('member_blood_type_key', type_='unique')
        batch_op.drop_constraint('member_emergency_phone_key', type_='unique')
        batch_op.drop_constraint('member_gender_key', type_='unique')
        batch_op.drop_constraint('member_last_name_key', type_='unique')
        batch_op.drop_constraint('member_name_key', type_='unique')
        batch_op.drop_constraint('member_objectives_key', type_='unique')
        batch_op.drop_constraint('member_payement_type_key', type_='unique')
        batch_op.drop_constraint('member_phone_key', type_='unique')
        batch_op.drop_constraint('member_profile_img_url_key', type_='unique')
        batch_op.drop_constraint('member_refered_key', type_='unique')
        batch_op.drop_constraint('member_stature_key', type_='unique')
        batch_op.drop_constraint('member_weight_key', type_='unique')

    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_constraint('membership_type_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_profile_img_url_key', type_='unique')
        batch_op.create_unique_constraint(None, ['number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_profile_img_url_key', ['profile_img_url'])

    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.create_unique_constraint('membership_type_key', ['type'])

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_unique_constraint('member_weight_key', ['weight'])
        batch_op.create_unique_constraint('member_stature_key', ['stature'])
        batch_op.create_unique_constraint('member_refered_key', ['refered'])
        batch_op.create_unique_constraint('member_profile_img_url_key', ['profile_img_url'])
        batch_op.create_unique_constraint('member_phone_key', ['phone'])
        batch_op.create_unique_constraint('member_payement_type_key', ['payement_type'])
        batch_op.create_unique_constraint('member_objectives_key', ['objectives'])
        batch_op.create_unique_constraint('member_name_key', ['name'])
        batch_op.create_unique_constraint('member_last_name_key', ['last_name'])
        batch_op.create_unique_constraint('member_gender_key', ['gender'])
        batch_op.create_unique_constraint('member_emergency_phone_key', ['emergency_phone'])
        batch_op.create_unique_constraint('member_blood_type_key', ['blood_type'])
        batch_op.create_unique_constraint('member_birthdate_key', ['birthdate'])
        batch_op.create_unique_constraint('member_address_key', ['address'])

    with op.batch_alter_table('discipline', schema=None) as batch_op:
        batch_op.create_unique_constraint('discipline_name_key', ['name'])

    # ### end Alembic commands ###
